-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 23:15:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adgtokyo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `adgtokyo` ;

-- -----------------------------------------------------
-- Schema adgtokyo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adgtokyo` DEFAULT CHARACTER SET utf8 ;
USE `adgtokyo` ;

-- -----------------------------------------------------
-- Table `adgtokyo`.`Work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adgtokyo`.`Work` ;

CREATE TABLE IF NOT EXISTS `adgtokyo`.`Work` (
  `id` VARCHAR(45) NOT NULL,
  `titleEn` VARCHAR(500) NULL,
  `titleLocal` VARCHAR(500) NULL,
  `DescriptionLocal` TEXT NULL,
  `formatLocal` VARCHAR(500) NULL,
  `formatEn` VARCHAR(500) NULL,
  `slug` VARCHAR(200) NULL,
  `status` VARCHAR(45) NULL,
  `descriptionEn` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adgtokyo`.`Entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adgtokyo`.`Entity` ;

CREATE TABLE IF NOT EXISTS `adgtokyo`.`Entity` (
  `id` VARCHAR(45) NOT NULL,
  `nameLocal` VARCHAR(500) NULL,
  `nameEn` VARCHAR(500) NULL,
  `slug` VARCHAR(200) NULL,
  `userId` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adgtokyo`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adgtokyo`.`Department` ;

CREATE TABLE IF NOT EXISTS `adgtokyo`.`Department` (
  `id` VARCHAR(45) NOT NULL,
  `workId` VARCHAR(45) NOT NULL,
  `titleLocal` VARCHAR(200) NULL,
  `titleEn` VARCHAR(200) NULL,
  `weight` SMALLINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Department_Work1_idx` (`workId` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Work1`
    FOREIGN KEY (`workId`)
    REFERENCES `adgtokyo`.`Work` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adgtokyo`.`Property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adgtokyo`.`Property` ;

CREATE TABLE IF NOT EXISTS `adgtokyo`.`Property` (
  `id` VARCHAR(45) NOT NULL,
  `keyLocal` VARCHAR(45) NULL,
  `keyEn` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `departmentId` VARCHAR(45) NOT NULL,
  `weight` SMALLINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Property_Department1_idx` (`departmentId` ASC) VISIBLE,
  CONSTRAINT `fk_Property_Department1`
    FOREIGN KEY (`departmentId`)
    REFERENCES `adgtokyo`.`Department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adgtokyo`.`PropertyHasEntity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adgtokyo`.`PropertyHasEntity` ;

CREATE TABLE IF NOT EXISTS `adgtokyo`.`PropertyHasEntity` (
  `entityId` VARCHAR(45) NOT NULL,
  `propertyId` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  `id` VARCHAR(45) NOT NULL,
  `subtextLocal` VARCHAR(200) NULL,
  `subtextEn` VARCHAR(200) NULL,
  `weight` SMALLINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Person_has_Property_Property1_idx` (`propertyId` ASC) VISIBLE,
  CONSTRAINT `fk_Person_has_Property_Property1`
    FOREIGN KEY (`propertyId`)
    REFERENCES `adgtokyo`.`Property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adgtokyo`.`History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adgtokyo`.`History` ;

CREATE TABLE IF NOT EXISTS `adgtokyo`.`History` (
  `id` VARCHAR(45) NOT NULL,
  `action` VARCHAR(45) NULL,
  `target` VARCHAR(45) NULL,
  `userId` VARCHAR(45) NULL,
  `workId` VARCHAR(45) NOT NULL,
  `propertyId` VARCHAR(45) NOT NULL,
  `entityId` VARCHAR(45) NOT NULL,
  `propertyHasEntityId` VARCHAR(45) NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT current_timestamp,
  `fromValue` TEXT NULL,
  `toValue` TEXT NULL,
  `departmentId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_History_Work1_idx` (`workId` ASC) VISIBLE,
  CONSTRAINT `fk_History_Work1`
    FOREIGN KEY (`workId`)
    REFERENCES `adgtokyo`.`Work` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adgtokyo`.`Release`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adgtokyo`.`Release` ;

CREATE TABLE IF NOT EXISTS `adgtokyo`.`Release` (
  `id` VARCHAR(45) NOT NULL,
  `year` VARCHAR(45) NULL,
  `regionLocal` VARCHAR(100) NULL,
  `regionEn` VARCHAR(100) NULL,
  `workId` VARCHAR(45) NOT NULL,
  `weight` SMALLINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Release_Work1_idx` (`workId` ASC) VISIBLE,
  CONSTRAINT `fk_Release_Work1`
    FOREIGN KEY (`workId`)
    REFERENCES `adgtokyo`.`Work` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
